export interface EmployeeDetail {
    employeeId:number;
    firstName:string;
    lastName:string;
    nationalId:string;
    birthDate:Date;
    birthPlace:string;
    adresses:string;
    contactNumbers:string;
    educationStatus:string;
    dateOfEntry:Date;
    leavingDate:Date;
    unitId:number;
    taskId:number;
    branchId:number;
    unitName:string;
    taskName:string;
    branchCityName:string;
}